(()=> {
    window.customFrame = {

        id:'smg',

        assetBase_string: 'http://localhost:8086/customSite',
        logo_url: '/images/gamedev.png',

        loading_background_color: '#001C30',
        loading_title_HTML: 'ShareMyGame',
        loading_first_string: 'The simple way to share games from GameDev.tv',

        lowerThird_color1: '#09460C',
        lowerThird_color2: '#0D6912',
        lowerThird_image: '/images/gamedev_padded.png',

        loading_strings_array:[
            'Adjusting Bell Curves',
            'Adding Hidden Agendas',
            'Aesthesizing Industrial Areas',
            'Applying Feng Shui Shaders',
            'Aligning Covariance Matrices',
            'Applying Theatre Soda Layer',
            'Attempting to Lock Back-Buffer',
            'Asserting Packed Exemplars',
            'Binding Sapling Root System',
            'Building Data Trees',
            'Breeding Fauna',
            'Bureacritizing Bureaucracies',
            'Calculating Llama Expectoration Trajectory',
            'Calculating Inverse Probability Matrices',
            'Calibrating Blue Skies',
            'Coalescing Cloud Formations',
            'Charging Ozone Layer',
            'Cohorting Exemplars',
            'Compounding Inert Tessellations',
            'Collecting Meteor Particles',
            'Compressing Fish Files',
            'Concatenating Sub-Contractors',
            'Computing Optimal Bin Packing',
            'Containing Existential Buffer',
            'Debunching Unionized Commercial Services',
            'Debarking Ark Ramp',
            'Deciding What Message to Display Next',
            'Decrementing Tectonic Plates',
            'Decomposing Singular Values',
            'Deleting Ferry Routes',
            'Depositing Slush Funds',
            'Depixelating Inner Mountain Surface Back Faces',
            'Destabilizing Economic Indicators',
            'Deunionizing Bulldozers',
            'Determining Width of Blast Fronts',
            'Dicing Models',
            'Downloading Satellite Terrain Data',
            'Diluting Livestock Nutrition Variables',
            'Exposing Flash Variables to Streak System',
            'Factoring Pay Scale',
            'Extracting Resources',
            'Fixing Election Outcome Matrix',
            'Flood-Filling Ground Water',
            'Flushing Pipe Network',
            'Gathering Particle Sources',
            'Generating Jobs',
            'Gesticulating Mimes',
            'Graphing Whale Migration',
            'Hiding Willio Webnet Mask',
            'Implementing Impeachment Routine',
            'Increasing Magmafacation',
            'Initializing Rhinoceros Breeding Timetable',
            'Initializing Robotic Click-Path AI',
            'Inserting Sublimated Messages',
            'Integrating Curves',
            'Integrating Illumination Form Factors',
            'Integrating Population Graphs',
            'Iterating Cellular Automata',
            'Lecturing Errant Subsystems',
            'Mixing Genetic Pool',
            'Modeling Object Components',
            'Mopping Occupant Leaks',
            'Normalizing Power',
            'Obfuscating Quigley Matrix',
            'Overconstraining Dirty Industry Calculations',
            'Partitioning City Grid Singularities',
            'Perturbing Matrices',
            'Pixalating Nude Patch',
            'Polishing Water Highlights',
            'Populating Lot Templates',
            'Preparing Sprites for Random Walks',
            'Prioritizing Landmarks',
            'Projecting Law Enforcement Pastry Intake',
            'Realigning Alternate Time Frames',
            'Reconfiguring User Mental Processes',
            'Relaxing Splines',
            'Removing Road Network Speed Bumps',
            'Removing Texture Gradients',
            'Removing Vehicle Avoidance Behavior',
            'Resolving GUID Conflict',
            'Reticulating Splines',
            'Retracting Phong Shader',
            'Retrieving from Back Store',
            'Reverse Engineering Image Consultant',
            'Routing Neural Network Infanstructure',
            'Scattering Rhino Food Sources',
            'Scrubbing Terrain',
            'Searching for Llamas',
            'Seeding Architecture Simulation Parameters',
            'Sequencing Particles',
            'Setting Advisor Moods',
            'Setting Inner Deity Indicators',
            'Setting Universal Physical Constants',
            'Sonically Enhancing Occupant-Free Timber',
            'Speculating Stock Market Indices',
            'Splatting Transforms',
            'Stratifying Ground Layers',
            'Sub-Sampling Water Data',
            'Synthesizing Gravity',
            'Synthesizing Wavelets',
            'Time-Compressing Simulator Clock',
            'Unable to Reveal Current Activity',
            'Weathering Buildings',
            'Zeroing Crime Network'
        ]
    }
})();

